### PR TITLE
Remove Mayavi 

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@uthpalaherath conda-forge is a bit picky with the package updates. It is highly recommended to open pull requests from a separate fork rather than updating the master branch directly.

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by uthpalaherath** [comment]
Hi @jan-janssen , 

My bad. Thanks for the advice. I will do so in the future. 

Best,
Uthpala

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
@uthpalaherath no problem, I believe moving away from mayavi is an important step. We made the same experience with https://github.com/pyiron/pyiron and finally we decided to use https://github.com/arose/nglview it integrates nicely with jupyter but it does not offer any electronic structure visualisation.

**Comment by uthpalaherath** [comment]
@jan-janssen yeah there's been a lot of issues related to mayavi so we switched to pyvista instead. I'll check those out, thanks!

Best,
Uthpala

**Pull request merged**
